### ISSUE TITLE
Error raised by puppeteer

### ISSUE THREAD

**Issue by david-mears** [spieglt/fb-photos#4]
```bash
fb-photos git:(master) node ./index.js
? Please enter your Facebook username (email address): kieuk@hotmail.co.uk
? Please enter your Facebook password: ************
(node:2621) UnhandledPromiseRejectionWarning: Error: Protocol error (Emulation.setDeviceMetricsOverride): Target closed.
    at /Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/Connection.js:182:12)
    at EmulationManager.emulateViewport (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/EmulationManager.js:41:20)
    at Page.setViewport (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/Page.js:814:54)
    at Page.<anonymous> (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/helper.js:112:23)
    at Function.create (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/Page.js:49:18)
    at async Browser._createPageInContext (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/Browser.js:177:18)
    at async main (/Users/daivdmears/projects/fb-photos/index.js:15:10)
  -- ASYNC --
    at Target.<anonymous> (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/helper.js:111:15)
    at Browser._createPageInContext (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/Browser.js:177:31)
    at async main (/Users/daivdmears/projects/fb-photos/index.js:15:10)
  -- ASYNC --
    at Browser.<anonymous> (/Users/daivdmears/projects/fb-photos/node_modules/puppeteer/lib/helper.js:111:15)
    at main (/Users/daivdmears/projects/fb-photos/index.js:15:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2621) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

MacOS 10.15.4
Node v14.5.0

**Comment by spieglt** [comment]
I haven't run this repo on a Mac in a while, and unfortunately I don't think I have any Catalina machines around but I can try with Big Sur. It looks like it's failing just trying to launch a Chrome window, at `page = await browser.newPage();`, which I haven't seen before.

**Comment by spieglt** [comment]
Huh, I am seeing the same behavior on Big Sur and Node 14.17. Interestingly it crashes at different points: once or twice it's almost gotten to where it starts downloading photos but crashes right before. Unfortunately the problem is not happening on Windows, so I have to assume it's something with Puppeteer on macOS.

**Comment by wsolorza** [comment]
Its happening on my windows 10

**Comment by wsolorza** [comment]
I can login to my account and there's no prompts I enter nothing happens freezes
https://a.cl.ly/geub6q0o

**Comment by spieglt** [comment]
@wsolorza You're saying it never even opens a Chromium window or displays an error message? That sounds like a different issue.
